#+TITLE: 暗时间
#+DATE: 2017-04-01
#+SETUPFILE: ~/myPro/octopress/setupfile.org
#+JEKYLL_LAYOUT: post
#+JEKYLL_CATEGORIES: 读书笔记 
#+JEKYLL_TAGS: 
#+JEKYLL_PUBLISHED: true

* 写在前面-碎碎念
  首先感谢《暗时间》这本书，也感谢作者刘未鹏，我因为这本书的循循善诱而开始写读书笔记，并一并重新建立了一个新的博客。否则我还不知道自己将会以什么样的方式，又会在什么样的时间才能重新开始写字。
  在年少轻狂的中学时代，我也曾是个爱鼓搞QQ空间，并在里面无病呻吟的孩子，写个三五行拾人牙慧的短句，便去呼朋唤友来给自己点赞、评论，大抵如此。如今我的QQ空间早已弃置，一是它早已不能任意修改和装饰，何况自己早也不再需要用这样的东西来突出自己，彰显个性；二是我也无甚了了可以记录并分享出来的了。
  我挺赞同书中书写是为了更好地思考的理论，作者说往往一篇文章在写之前只是寥寥几点，但在写的过程中句子却会像自己有生命一样从笔下冒出来。这是我感同身受的，同时也是少年时期自己喜欢写一些东西的主要原因。
  停笔辍耕的很长一段时间里，我不是没想过要重新开始，但每每提起笔却又不知道该写些什么；又或者想写一个故事，通过一些人和事来阐述一些道理，可是写了两三段，回过头重读一遍，觉得文笔幼稚得把自己都逗乐了。
  停下了写字，倒不是同样停下了思考，恰恰相反，我正是自觉知识匮乏和理论贫瘠，所以极其渴望地，孜孜不倦地想要学习各种新鲜的，自己感兴趣的事物。
  我自觉是个腼腆而内敛的人，不善与人交往，所以在青春期选择用文字来表达感情和见解，如今已将近而立之年，成长似乎并未给我的人际关系带来太大的改善，所幸我遇到了我的爱人——菠萝。与她交流逐渐成为了我思考和提升自己的新的方式，与之相比，停下写字的遗憾似乎变得不那么重要了。
  然而，书写还是有自己不可被替代的部分，譬如记录思想过程，与自己对话，乃至书写引发的思考都可能和与人交流引发的思考不尽相同。在《暗时间》的劝诱下，在菠萝的鼓励下，我以读书笔记的形式重新开始写文字。所以，感谢《暗时间》，也感谢菠萝。
{{{more}}}
* 写在前面-书的分类
  作者提到一些伴随他的好习惯： *读书挑剔，只读经典* ，深以为然。
  并且我想对此稍加补充：我把市场上纷繁复杂的书籍分为两个大类，“爸爸”类和“儿子”类，即许多书籍其实是借由另一些经典书籍中的部分理论延伸拓展而来，所以称为“儿子”类，这类书籍往往是最多的，其蕴含的道理也是浅显易懂的。
  关于“儿子”类的书籍大可不做阅读，直接追根溯源去找它的“爸爸”，因为在“爸爸”中可以读到“儿子”的几乎所有内容，而且你还能读到其它更多类似的，一系列的理论。“爸爸”类，是为经典。
  关于经典，我还有更细致的归类，分为三类：
      第三类经典：大多阐述了某些专业领域内的新的发现，或对于事物的深刻见解。《暗时间》便在此列，除此之外，私以为《三体》系列，《自私的基因》如是。
      第二类经典：在第三类的基础上，由于其专业性太强或寓意太过深刻，通读和彻悟起来往往需要很长，甚至超过一年的时间。如《时间简史》、《生命不能承受之轻》、《算法导论》。
      第一类经典：自然是在第二类基础上，经典中的经典，不但读懂需要很长时间，甚至作者本人也为了其中的道理追寻努力了许久，或是倾其一生。这类书籍本人愚钝还未拜读，举例仅供参考：《易经》、《GEB》。
  总的来说，我对书籍的分类分为四个大类，第一类，第二类，第三类和普通类，取 /一生二，二生三，三生万物/ 之意。
* 原始大脑与现代大脑：自我与超我 
* 父母的影响
* 读书笔记和博客
* Unknown Unknown
